#!/bin/bash

shun="${SHUNFILE:-.shun}"

topdir="$(git rev-parse --show-toplevel)"
oldpwd="${PWD}"
cd "$topdir"

shunfile="${topdir}/${shun}"
test -f "$shunfile" || shunfile="$HOME/${shun}"
test -f "$shunfile" || unset shunfile



_git-shunned () {
  git ls-files -v | sed -ne 's/^[[:lower:]] //p' | grep .
  }

[ "$1" ] || set -- automagic

while [ "$1" ]; do case "$1" in
  --|a|add)  shift; break ;;

  m|magic|auto|automa[tg]ic)
    shift
    test -f "$shunfile" || {
      echo >&2 "$0: can't find shun file $shunfile"
      exit 1
      }
    cat "$shunfile" | xargs git shun add
    echo >&2 "Added from $shunfile:"
    git shun list
    exit 0 ;;

  l|ls|list)
    shift
    fmt="%s"

    for arg; do case "$arg" in
      -c|--count) c=1; shift ;;
      -n|--no-newline) n=1; shift ;;
      -r|--relative) rel=1; shift ;;
      *) fmt="$*"; break ;;
      esac; done

    [ "$rel" ] && cd "$OLDPWD"
    shunned="$(_git-shunned)" || exit 1

    [ ! $n ] && fmt="$fmt\n"

    [ $c ] && shunned="$(echo "$shunned"|wc -l|xargs -n1)"

    echo "$shunned" | xargs -n1 printf "$fmt"
    exit 0 ;;

  r|rm|remove)
    shift
    [ "$1" ] || { echo >&1 "$0: remove what?"; exit 1; }
    case "$1" in
      -a|--all)
        git shun list | xargs git shun remove
        exit 0 ;;
      --) shift ;;
      esac

      git update-index --no-assume-unchanged "$@"
      exit 0 ;;

  c|cl|clr|clear|n|no|none)
    git shun remove --all
    exit 0 ;;

  w|wr|write)
    shift
    test -f "$shunfile" || {
      echo >&2 "$0: can't find shun file $shunfile"
      exit 1
      }
    dest="$shunfile"
    case "$1" in -a|--append) append=1; shift ;; esac
    [ "$1" ] && dest="$1"

    if [ "$append" ]; then
      { cat "$shunfile" <(git shun list) | sort -u; } >> "$dest"
    else
      { git shun list | sort -u; } > "$dest"
    fi

    echo >&2 "Written to $dest:"
    cat "$dest"
    exit 0 ;;

  s|st|status)
    shift
    git status --short "$@"
    ( cd "$oldpwd"; git shun list --relative '\033[1;30m.. %s\033[0m' )
    exit 0 ;;

  ''|-h|--help)
    printf "No help. Just code.\n\n"
    cat "$0"
    exit 0 ;;

  *)
    break ;;
  esac; done

# add:
git update-index --assume-unchanged "$@"

